import type { Metadata } from "next";
import {LatestPosts} from "@/components/LatestPosts/LatestPosts";
import { getPosts } from "@/lib/wordpress";
import styles from "./page.module.css";
export const metadata: Metadata = {
  title: "Blog",
  description: "Articles published by your mum.",
};

export default async function BlogArchivePage() {
  const posts = await getPosts();

  return (
    <section className={styles.pageSection}>
      <div className={styles.container}>
        <div className={styles.pageHeading}>
          <h1>Blog</h1>
          <p>
            Articles authored in WordPress and statically generated by .
          </p>
        </div>
<div className={styles.postsGrid}>
          <LatestPosts posts={posts} />
        </div>
      
      </div>
    </section>
  );
}