import type { Metadata } from "next";
import { PostCard } from "@/components/PostCard/PostCard";
import { getPosts } from "@/lib/wordpress";

export const metadata: Metadata = {
  title: "Blog",
  description: "Articles published from the headless WordPress CMS.",
};

export default async function BlogArchivePage() {
  const posts = await getPosts();

  return (
    <section className="page-section">
      <div className="container">
        <div className="page-heading">
          <h1>Blog</h1>
          <p>
            Articles authored in WordPress and statically generated by Next.js.
          </p>
        </div>

        {posts.length > 0 ? (
          <div className="post-grid">
            {posts.map((post) => (
              <PostCard key={post.id} post={post} />
            ))}
          </div>
        ) : (
          <p>No published WordPress posts were returned.</p>
        )}
      </div>
    </section>
  );
}